- instrument: DP1
  channel: 1
  min_current: 0.003
  max_current: 0.02
- instrument: DP1
  channel: 2
  min_current: 0.0000
  max_current: 0.0015
- instrument: DP1
  channel: 3
  min_current: 0.25
  max_current: 0.45
